name: flutter_map_example
description: Example application for 'flutter_map' package
publish_to: "none"
version: 7.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map:
  flutter_map_cancellable_tile_provider: ^3.0.0
  flutter_map_geojson: ^1.0.8
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  latlong2: ^0.9.1
  proj4dart: ^2.1.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  url_strategy: ^0.2.0
  vector_math: ^2.1.4
  location: ^6.0.2

dependency_overrides:
  flutter_map:
    path: ../

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/map/anholt_osmbright/12/2177/
    - assets/map/anholt_osmbright/12/2178/
    - assets/map/anholt_osmbright/12/2179/
    - assets/map/anholt_osmbright/12/2180/
    - assets/map/anholt_osmbright/12/2181/
    - assets/map/anholt_osmbright/13/4354/
    - assets/map/anholt_osmbright/13/4355/
    - assets/map/anholt_osmbright/13/4356/
    - assets/map/anholt_osmbright/13/4357/
    - assets/map/anholt_osmbright/13/4358/
    - assets/map/anholt_osmbright/13/4359/
    - assets/map/anholt_osmbright/13/4360/
    - assets/map/anholt_osmbright/13/4361/
    - assets/map/anholt_osmbright/13/4362/
    - assets/map/anholt_osmbright/13/4363/
    - assets/map/anholt_osmbright/14/8709/
    - assets/map/anholt_osmbright/14/8710/
    - assets/map/anholt_osmbright/14/8711/
    - assets/map/anholt_osmbright/14/8712/
    - assets/map/anholt_osmbright/14/8713/
    - assets/map/anholt_osmbright/14/8714/
    - assets/map/anholt_osmbright/14/8715/
    - assets/map/anholt_osmbright/14/8716/
    - assets/map/anholt_osmbright/14/8717/
    - assets/map/anholt_osmbright/14/8718/
    - assets/map/anholt_osmbright/14/8719/
    - assets/map/anholt_osmbright/14/8720/
    - assets/map/anholt_osmbright/14/8721/
    - assets/map/anholt_osmbright/14/8722/
    - assets/map/anholt_osmbright/14/8723/
    - assets/map/anholt_osmbright/14/8724/
    - assets/map/anholt_osmbright/14/8725/
    - assets/map/anholt_osmbright/14/8726/
    - assets/map/anholt_osmbright/14/8727/
    - assets/map/epsg3413/amsr2.png
    - assets/type_car/vf.png
    - assets/type_car/testla_model_s.png
    - assets/type_car/kia_soul_ev.png
    - assets/type_car/honda_e.png
    - assets/type_car/hyundai_kona_electric.png
    - assets/type_car/mg_zs_ev.png
    - assets/type_car/nissan_leaf.png
    - assets/type_car/peugeot_e208.png
    - assets/type_car/polestar_2.png
    - assets/type_car/tesla_model_3.png
    - assets/type_car/volkswagen_id3.png
    - assets/bottom_navigator/ic_home.svg
    - assets/bottom_navigator/ic_list_order.svg
    - assets/bottom_navigator/ic_profile.svg
    - assets/bottom_navigator/ic_message.svg
    - assets/bottom_navigator/ic_map.svg
    - assets/home/bg_home.png
    - assets/home/ic_notice.svg
    - assets/home/ic_add.svg
    - assets/home/ic_search.svg
    - assets/home/ic_scan.svg
    - assets/home/ic_check_rate.svg
    - assets/home/ic_nearby_drop.svg
    - assets/home/ic_others.svg
    - assets/home/ic_help.svg
    - assets/home/ic_wallet.svg
    - assets/home/ic_order.svg
    - assets/home/ic_package.svg
    - assets/mapbox-logo-white.png
    - assets/google_icon.png
    - assets/apple_icon.png
    - assets/background_profile.png
    - assets/ic_lock.png
    - assets/ic_glo.png
    - assets/ic_noti.png
    - assets/ic_help.png
    - assets/ic_security.png
    - assets/ic_team.png
    - assets/
